// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMj5Rr65TqWLOMYiG2NLdZSymwmJshH1g',
    appId: '1:760082000923:web:851c2231e05b8ec5a3dcbe',
    messagingSenderId: '760082000923',
    projectId: 'snevva-aef81',
    authDomain: 'snevva-aef81.firebaseapp.com',
    storageBucket: 'snevva-aef81.firebasestorage.app',
    measurementId: 'G-3YR5EVMEPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUAz5H5yHgpZl8DHnEScp_O3weEXndQIE',
    appId: '1:760082000923:android:d64810cdaedd774da3dcbe',
    messagingSenderId: '760082000923',
    projectId: 'snevva-aef81',
    storageBucket: 'snevva-aef81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fAwHuZiDkG80V-eHNHLkxzVdQCVmOOc',
    appId: '1:760082000923:ios:3a1373b6a0b5a914a3dcbe',
    messagingSenderId: '760082000923',
    projectId: 'snevva-aef81',
    storageBucket: 'snevva-aef81.firebasestorage.app',
    iosBundleId: 'com.example.doc',
  );
}
